# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Le Mango Tree
email: contact@lemangotree.com
description: > # this means to ignore newlines until "baseurl:"
  Le Mango Tree est le premier bar à jus et smoothies bowls 100 % naturel d'Hossegor.
baseurl: /lemangotree-v2
url: "http://lemangotree.com" # the base hostname & protocol for your site
instagram_username: lemangotree
facebook_username: lemangotree

# Build settings
markdown: kramdown
